### ISSUE TITLE
Async Throws support for initializers

### ISSUE THREAD

**Issue by zunda-pixel** [apple/swift-format#410]
```swift
init() async throws {
}
```

**Comment by allevato** [comment]
This is working on `main`, since the underlying issue was fixed in https://github.com/apple/swift-syntax/pull/499. I don't know if there are plans to cherry-pick that PR and its corresponding apple/swift PR into the 5.7 branch this late, so my recommendation would be to build from `main` if you need this.

**Comment by ra1028** [comment]
@allevato 

It seems that swift-syntax has released version [0.50700.1](https://github.com/apple/swift-syntax/releases/tag/0.50700.1) that includes the fix.
Do you plan to release swift-format `0.50700.1` as well soon? 
main branch isn't compilable as of now for some reason, and I'm sure that it happens a lot because main is not always stable given it depends on main branch of swift-syntax.

**Comment by allevato** [comment]
AFAIK swift-syntax 0.50700.1 does not include #499; it only contained a fix for the `if let` shorthand syntax.
