### ISSUE TITLE
Unable to build: Invalid manifest / error: no such module 'PackageDescription'

### ISSUE THREAD

**Issue by kaoz3000** [apple/swift-format#432]
Hi,
when I try to install swift-format:

```
VERSION=0.50700.0
git clone https://github.com/apple/swift-format.git
cd swift-format
git checkout "tags/$VERSION"
swift build -c release
```
I get this error:

> iMac:swift-format user$ swift build -c release
> error: 'swift-format': Invalid manifest
> /Users/userswift-format/Package.swift:15:8: error: no such module 'PackageDescription'
> import PackageDescription
>       ^

whats going wrong?

MacOS Version 12.6
Xcode 14.0.1
Intel iMac 2017

**Comment by kaoz3000** [comment]
OK, it was my fault:
Command Line Tools where not set here :
Xcopy -> Preferences -> Locations

**Comment by hfmanson** [comment]
This error also occurs when you update Xcode and don't reopen terminal

**Comment by rockwotj** [comment]
@kaoz3000 you saved me a lot of hairpulling and debugging. Thank you! 🙏

**Comment by Kuro7070** [comment]
Hello, I got the same error like @kaoz3000. I already installed the command line tool and it is set under location. But I still get the error.
What I did:
1. open Terminal
2. insert the following code
`VERSION=0.50700.0  # replace this with the version you need
git clone https://github.com/apple/swift-format.git
cd swift-format
git checkout "tags/$VERSION"
swift build -c release`
4. after the build command does the same error like @kaoz3000 appear

Am I missing something? If I did something wrong please tell me, because I'm new in the MacOS Universe and Swift Language.
