### ISSUE TITLE
Formatting issue with placeholder

### ISSUE THREAD

**Issue by HassanTaleb90** [apple/swift-format#462]
Issue: **Unable to format code when we have a placeholder.**

Code example:
class <#name#>: <#super class#> {
    <#code#>
}

**diagnostic:
2:5: expected 'func' in function
2:13: expected parameter clause in function signature** 

<img width="577" alt="Screenshot 2022-12-17 at 5 22 20 PM" src="https://user-images.githubusercontent.com/49780321/208249215-93145b6e-6208-4658-87c4-5ff0022b3438.png">

example 2: **(the placeholder "<#code#>" must be formatted)**
<img width="445" alt="Screenshot 2022-12-17 at 5 28 56 PM" src="https://user-images.githubusercontent.com/49780321/208249275-24f6e28a-5bb9-4b3e-b806-8f5fcfdd57d0.png">

**Comment by allevato** [comment]
Situations like this are tricky because we don't currently don't make any attempt to format invalid code, which that is.

The parse tree for your example looks like this:

```
SourceFileSyntax children=2
  0: CodeBlockItemListSyntax children=1
    0: CodeBlockItemSyntax children=1
      0: ClassDeclSyntax children=4
        0: classKeyword
        1: identifier("<#name#>")
        2: TypeInheritanceClauseSyntax children=2
          0: colon
          1: InheritedTypeListSyntax children=1
            0: InheritedTypeSyntax children=1
              0: SimpleTypeIdentifierSyntax children=1
                0: identifier("<#super class#>")
        3: MemberDeclBlockSyntax children=3
          0: leftBrace
          1: MemberDeclListSyntax children=1
            0: MemberDeclListItemSyntax children=1
              0: FunctionDeclSyntax children=3
                0: funcKeyword MISSING
                1: identifier("<#code#>")
                2: FunctionSignatureSyntax children=1
                  0: ParameterClauseSyntax children=3
                    0: leftParen MISSING
                    1: FunctionParameterListSyntax
                    2: rightParen MISSING
          2: rightBrace
  1: eof
```

It's actually really helpful that the `name` and `super class` placeholders come through just as identifiers, because we could treat those opaquely. The problematic node is `code`, since the parser tries to parse it as a function declaration with missing parts.

It looks like placeholders in expression positions degrade nicely to an `EditorPlaceholderExprSyntax` node, so something like `for <#index#> in <#collection#> { <#stmt#> }` comes all the way through without diagnostics. So, a placeholder in a `MemberDeclList` might uniquely be a problem that could be handled more gracefully.

@ahoppen do you think it would make sense to provide an `EditorPlaceholderDeclSyntax` that could be slotted in as the child of a `MemberDeclListItemSyntax` to support this specific case? Or maybe some other approach to make this produce a cleaner tree than trying to assume a broken function?

**Comment by ahoppen** [comment]
I think we could treat editor placeholders as unexpected tokens in member decl lists.

**Comment by ahoppen** [comment]
Here we go: https://github.com/apple/swift-syntax/pull/1188
