### ISSUE TITLE
Implement a warning or error if an unrecognized Rule is specified in .swift-format

### ISSUE THREAD

**Issue by natikgadzhi** [apple/swift-format#607]
Right now, if one made a typo in a rule name in `.swift-format` and then ran the formatter, it will ignore the typo and, obviously, not apply the rule.

I was working on https://github.com/apple/swift-syntax/pull/2145, and of course, that's precisely what I did. _Oh, nice, our imports are already ordered, right?_

## Proposed solution
Since we know the list of all available rules, we could verify that each string in the Rules block matches an existing rule.

```swift
// Config.swift
//
// If the `rules` key is not present at all, default it to the built-in set
// so that the behavior is the same as if the configuration had been
// default-initialized. To get an empty rules dictionary, one can explicitly
// set the `rules` key to `{}`.
self.rules =
  try container.decodeIfPresent([String: Bool].self, forKey: .rules)
  ?? defaults.rules
```

It should be relatively easy, we could just generate an `enum` with all rule names, and use that as the key when decoding the rules.

Should I draft this in a PR?

**Comment by allevato** [comment]
This is a great idea for improvement, but I think it's a little bit more complicated than you've described here.

The configuration decoding logic doesn't have any way to pass information out of it other than "here's a successfully parsed config" or "here's an error because it failed". So if we want a warning, we have to check it in the frontend after decoding it; otherwise, we can make it an error during the actual decoding process.

The only real value to a warning—aside from just being a little more relaxed—would be to retain compatibility of newer config files with older versions of swift-format, but I don't think that's something we really need to do. So just throwing an error would be easier to implement.

I don't know if we need all the ceremony of generating a new enum for this, though. We already generate a `Dictionary` with all the rule names as keys [here](
https://github.com/apple/swift-format/blob/main/Sources/SwiftFormatConfiguration/RuleRegistry%2BGenerated.swift), so after decoding `self.rules` we could just check that all the decoded rule names exist in that dictionary (doesn't matter what the value is), and throw a decoding error if there's an unrecognized name.

Feel free to send a PR!

**Comment by natikgadzhi** [comment]
> The configuration decoding logic doesn't have any way to pass information out of it other than "here's a successfully parsed config" or "here's an error because it failed". So if we want a warning, we have to check it in the frontend after decoding it; otherwise, we can make it an error during the actual decoding process.

I've explored a bit yesterday, and yep — I think one of the questions is at what level should that check be. It could be in `Configuration.decode`, but that `Codable` implementation, in theory, doesn't have to be aware of any domain logic. It can just parse JSON into what it states — `[String:Bool]`.

Then, there's `ConfigurationLoader` that's relatively simple — perhaps that's the right level. But I gravitate to the next one: 

We could put that into `Frontend`. I'm looking to confirm _how exactly_ it loads config, seems like it has at least two ways to do it, but essentially, we could validate the configuration _after we load it_, and emit a warning in that context, which is nice and easy because `Frontend` has `diagnosticsEngine` on it already.

> The only real value to a warning—aside from just being a little more relaxed—would be to retain compatibility of newer config files with older versions of swift-format, but I don't think that's something we really need to do. So just throwing an error would be easier to implement.

If we decide to go with an error, than the simplest solution by far is a check in `Configuration.decode`, like this:

```swift
```
