### ISSUE TITLE
Trailing commas on multi-line collections (bug)

### ISSUE THREAD

**Issue by HassanTaleb90** [apple/swift-format#620]
There is a bug when trailing commas on multi-line collections is `true`

Example:
```
let MyCollection = [1, 2, 3] 
```
Result: let MyCollection = [1, 2, 3] 
Expected: let MyCollection = [1, 2, 3,]

**Comment by allevato** [comment]
For posterity (you closed the issue as I was typing this), `[1, 2, 3]` is what I would expect here, because we would only want the trailing comma to apply _when the line wraps after the last element of the collection_.

The name of the configuration setting doesn't go into that much detail, but that's a concession made to keep it from being too long.
