### ISSUE TITLE
`AllPublicDeclarationsHaveDocumentation` warns on overridden methods 

### ISSUE THREAD

**Issue by aperkov** [apple/swift-format#651]
I recently used Homebrew to upgrade to `swift-format 509.0.0`.

The behaviour of the `AllPublicDeclarationsHaveDocumentation` rule has changed:

- Previously overridden methods did not cause the rule to trigger a warning.
- Now they do.

I'm not sure if this was intentional or not - there doesn't seem to be any mention in the release notes.

The behavioural change seems to have happened in https://github.com/apple/swift-format/pull/609 

`AllPublicDeclarationsHaveDocumentation.swift` now contains:

```
guard
       DocumentationCommentText(extractedFrom: decl.leadingTrivia) == nil,
       modifiers.contains(anyOf: [.public, .override])
```

Whereas previously it contained a guard that `modifiers` does *not* contain `override`:

```
guard
       DocumentationCommentText(extractedFrom: decl.leadingTrivia) == nil,
       let mods = modifiers, mods.has(modifier: "public") && !mods.has(modifier: "override")
```

**Comment by allevato** [comment]
Thanks for the report! I noticed that we don't actually have test coverage for this case, and in the process of adding test coverage for it, it revealed that the rule—and a few others—were written incorrect to support unit testing anyway. So this became a whole... thing.

I'll do a targeted fix for this specific issue and then fix the other underlying issues with the tests separately, since it might have broader-ranging impact, and I can cherry-pick the specific fix into a 509 dot release.
