### ISSUE TITLE
Adjust indentation when using multiple if-let expressions

### ISSUE THREAD

**Issue by DevYeom** [apple/swift-format#740]
Tested on `510.1.0` with 2 spaces for indentation.

Input:
```swift
func test() {
  if let abc,
     let def
  {
    print("hello")
  }
}
```

Output:
```swift
func test() {
  if let abc,
    let def
  {
    print("hello")
  }
}
```

Input code was formatted using Re-Indent (`⌃I`) in Xcode.
It appears that the default indentation rule was applied.
How about adding a rule for adjusting the indentation of multiple `if-let` expressions?

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://127922850

**Comment by allevato** [comment]
We made a fairly conscious decision early on to keep all indentation sizes fixed, rather than offering context-based variant indentations.

It's something we could revisit in the future, but for now, this is by design, and I want to be deliberate about increasing the surface area of the formatter's configurability. Each new setting creates the potential for interactions with other settings, making it harder to reason about.

**Comment by DevYeom** [comment]
Thanks!
